#!/bin/sh

# ddf分割文件命令
# 默认每个文件512MB
# 第一个参数是文件名，第二个参数是分割后每个文件的大小。
# 第二个参数的单位为KB
# 生成的文件格式为： filename.1.ddf filename.2.ddf 等
# author: yongfu (rickie622 at gmail dot com)

# usage: ddf filename [subsize(kb)]

# 判断参数个数
if [ $# -eq 0 ] || [ $# -gt 2 ]; then
    echo "usage: ddf filename [subsize(kb)]"
    exit 1
fi

# 使用脚本是第一参数是要分割的文件名
Filename=$1 
Filesize=0

# 验证文件名是否正确，文件大小是否为0
if [ ! -s $Filename ];then
    echo "Error:The file is not exsit or the file is empty."
    exit 1
fi

# 前面已验证文件存在，所以目录必存在
FilePath=$(dirname $Filename)

# 创建Filename的目录，为后面方便合并
Path=${FilePath}/${Filename}_ddf
mkdir -p $Path

# 文件的字节数
Filesize=$(du -b $Filename |awk '{print $1}')

# 判断脚本的第二个参数
InputSubsize=$2
if [ -z $InputSubsize ]; then
    # 默认值512M
    Subsize=524288
else
    # 判断是否为整数
    if [[ $InputSubsize =~ ^[1-9][0-9]*$ ]]; then
        Subsize=$InputSubsize
    else
        echo "usage: ddf filename [subsize(kb)]"
        echo "The second argument should be an integer!"
        exit 1
    fi
fi

# 若文件本身比分隔值还小，则不分割
if [ $Filesize -le $Subsize ]; then
    echo "usage: ddf filename [subsize(kb)]"
    echo "The second argument should be smaller than the filesize."
    exit 1
fi

#计算需要分割为几个文件
SubfileByte=$(expr $Subsize \* 1024 )
Subfilenum=$(expr $Filesize / $SubfileByte )
Subfilemod=$(expr $Filesize % $SubfileByte )
if [ $Subfilemod -ne 0 ];then
    Subfilenum=$(expr $Subfilenum + 1)
fi

#将文件分割
echo "$Filename will be divided into *$Subfilenum* pieces"
i=1
skipnum=0
while [ $i -le $Subfilenum ]
do
    echo "$Filename.$i.ddf"
    dd if=$Filename of="$Path/$Filename.$i.ddf" bs=1024 count=$Subsize skip=$skipnum
    i=$(expr $i + 1)
    skipnum=$(expr $skipnum + $Subsize)
done
echo "$Filename has been divided into $Subfilenum"
echo "Done !"
